---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: debezium-postgresql
  namespace: confluent
spec:
  class: "io.debezium.connector.postgresql.PostgresConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    connection.url: ${file:/mnt/secrets/postgres-credentials/plain.txt:connection}
    mode: "incrementing"
    incrementing.column.name: "id"
    timestamp.column.name: "modified"
    topic.prefix: "groceries-"
    poll.interval.ms: "1000"