---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: postgres-jdbc-grocery-shop
  namespace: confluent
spec:
  class: "io.confluent.connect.jdbc.JdbcSourceConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    connection.url: ${file:/mnt/secrets/postgres-credentials/plain.txt:connection}
    schema.pattern: "grocery_shop"
    catalog.pattern: "grocery_shop"
    table.whitelist: "sellers,customers,products,orders"
    mode: "timestamp"
    timestamp.column.name: "last_update_time"
    topic.prefix: "postgres.grocery_shop."
    poll.interval.ms: "1000"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.basic.auth.credentials.source: "USER_INFO"
    value.converter.schema.registry.basic.auth.user.info: ${file:/mnt/secrets/ccloud-sr-credentials/basic.txt:username}:${file:/mnt/secrets/ccloud-sr-credentials/basic.txt:password}
    value.converter.schema.registry.url: "https://cc-sr-url"
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.basic.auth.credentials.source: "USER_INFO"
    key.converter.schema.registry.basic.auth.user.info: ${file:/mnt/secrets/ccloud-sr-credentials/basic.txt:username}:${file:/mnt/secrets/ccloud-sr-credentials/basic.txt:password}
    key.converter.schema.registry.url: "https://cc-sr-url"
    transforms: "valueToKey,extractField"
    transforms.valueToKey.type: "org.apache.kafka.connect.transforms.ValueToKey"
    transforms.valueToKey.fields: "id"
    transforms.extractField.type: "org.apache.kafka.connect.transforms.ExtractField$Key"
    transforms.extractField.field: "id"
