apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: postgres-volume # Sets PV name
  labels:
    type: local # Sets PV's type
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/data